### ISSUE TITLE
Integration 2: Domainmodel from Anmeldung-Frontend into Domainmodel Backend

### ISSUE THREAD

**Issue by jonashackt** [digital-bauhaus/Ferienpass-Admin#17]

**Comment by kleinfreund** [comment]
The frontend of micro service 1 will make an HTTP request to `/api/form` in order to retrieve the relevant information it needs to display the form. The form data is expected to be formatted like it is in this file: https://github.com/digital-bauhaus/Ferienpass-Anmeldung/blob/master/frontend/static/form-data.json.
